server:
  port: 8082

spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DATASOURCE_URL}
    username: ${AUTH_DATASOURCE_USERNAME}
    password: ${AUTH_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

springdoc:
  openapi:
    servers:
      - url: ${API_GATEWAY_URL}
        description: "API Gateway"