server:
  port: 8083

spring:
  application:
    name: resource-catalog-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  datasource:
    url: ${RESOURCE_DATASOURCE_URL:jdbc:postgresql://postgres-resource:5432/resource_db}
    username: ${RESOURCE_DATASOURCE_USERNAME:user}
    password: ${RESOURCE_DATASOURCE_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect