name: Resource Service CI

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - 'resource-catalog-service/**'
  pull_request:
    branches: [ "develop", "main" ]
    paths:
      - 'resource-catalog-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and run tests with Maven
        run: |
          cd resource-catalog-service
          mvn clean test -DAPI_GATEWAY_URL=http://localhost